### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tcsdmaic** [timeff/selenium-ide-js-converter#1]
Where / How exactly do you use the command "require('selenium-ide-js-converter')('html folder name','js folder name')" in order to convert the IDE html file??
Thank you!

**Comment by timeff** [comment]
Hey @tcsdmaic

Basically, just create new JavaScript file and put "require('selenium-ide-js-converter')('html folder name','js folder name')" on it. Then, just run the file (maybe using "node that_filename.js"

I've updated README.md. Hope that might help you :)
